---
- hosts: deploy

  vars:
    # workdir: /opt/futurico/deploy
    workdir: /vagrant
    deploy_repo: https://github.com/futuware/kapellmeister.git

  roles:
    - role: docker.ubuntu
      docker_group_members:
        - "{{ ansible_ssh_user }}"
      sudo: true

  tasks:
    - name: Ensure docker service is running
      service: name=docker state=started enabled=yes

    - name: Ensure git is installed
      apt: name=git state=present
      sudo: true

    - name: Add ansible repo
      apt_repository: repo='ppa:ansible/ansible'
      sudo: true

    - name: Install ansible
      apt: name=ansible state=present
      sudo: true

    - name: Ensure workdir exists
      file: path={{ workdir }} state=directory owner={{ ansible_ssh_user }}
      sudo: true

#    - name: Ensure deploy code is present and up-to-date
#      git: repo={{ deploy_repo }} dest={{ workdir }} update=true

    - name: Install depl util
      shell: python setup.py develop chdir={{ workdir }}/depl
      sudo: true

    - name: Ensure bash config is included
      lineinfile: dest=~/.bashrc line="if [ -f ~/.bashrc-local ]; then source ~/.bashrc-local; fi"

    - name: Setup shell goodies
      template: src=templates/bashrc-local.j2 dest=~/.bashrc-local
